export const Jugadores = [
  {
    id: 1,
    nombre: "Caty",
    apellido: "Yapp",
    edad: 22,
    sexo: "Female",
    posicion: "Arquero",
    salario: 55,
    pieDominante: "Izquierdo",
  },
  {
    id: 2,
    nombre: "Linn",
    apellido: "McEniry",
    edad: 11,
    sexo: "Male",
    posicion: "Mediocampista",
    salario: 17,
    pieDominante: "Izquierdo",
  },
  {
    id: 3,
    nombre: "Franz",
    apellido: "Micka",
    edad: 58,
    sexo: "Male",
    posicion: "Delantero",
    salario: 86,
    pieDominante: "Izquierdo",
  },
  {
    id: 4,
    nombre: "Atalanta",
    apellido: "Perrycost",
    edad: 44,
    sexo: "Female",
    posicion: "Delantero",
    salario: 38,
    pieDominante: "Izquierdo",
  },
  {
    id: 5,
    nombre: "Grayce",
    apellido: "Wheldon",
    edad: 61,
    sexo: "Female",
    posicion: "Arquero",
    salario: 46,
    pieDominante: "Izquierdo",
  },
  {
    id: 6,
    nombre: "Norbie",
    apellido: "Janc",
    edad: 88,
    sexo: "Male",
    posicion: "Defensor",
    salario: 80,
    pieDominante: "Derecho",
  },
  {
    id: 7,
    nombre: "Howard",
    apellido: "Levington",
    edad: 73,
    sexo: "Male",
    posicion: "Delantero",
    salario: 93,
    pieDominante: "Izquierdo",
  },
  {
    id: 8,
    nombre: "Robin",
    apellido: "Handman",
    edad: 41,
    sexo: "Male",
    posicion: "Delantero",
    salario: 64,
    pieDominante: "Izquierdo",
  },
  {
    id: 9,
    nombre: "Cacilie",
    apellido: "Panketh",
    edad: 74,
    sexo: "Female",
    posicion: "Arquero",
    salario: 90,
    pieDominante: "Izquierdo",
  },
  {
    id: 10,
    nombre: "Orville",
    apellido: "Bottomore",
    edad: 7,
    sexo: "Male",
    posicion: "Defensor",
    salario: 30,
    pieDominante: "Izquierdo",
  },
  {
    id: 11,
    nombre: "Etienne",
    apellido: "Ashurst",
    edad: 73,
    sexo: "Male",
    posicion: "Delantero",
    salario: 5,
    pieDominante: "Derecho",
  },
  {
    id: 12,
    nombre: "Lilyan",
    apellido: "Reynoldson",
    edad: 37,
    sexo: "Female",
    posicion: "Mediocampista",
    salario: 74,
    pieDominante: "Izquierdo",
  },
  {
    id: 13,
    nombre: "Cyndia",
    apellido: "Bugbee",
    edad: 12,
    sexo: "Female",
    posicion: "Arquero",
    salario: 18,
    pieDominante: "Derecho",
  },
  {
    id: 14,
    nombre: "Durward",
    apellido: "Loughran",
    edad: 42,
    sexo: "Male",
    posicion: "Defensor",
    salario: 93,
    pieDominante: "Derecho",
  },
  {
    id: 15,
    nombre: "Lowell",
    apellido: "Pragnell",
    edad: 3,
    sexo: "Male",
    posicion: "Delantero",
    salario: 90,
    pieDominante: "Izquierdo",
  },
  {
    id: 16,
    nombre: "Marge",
    apellido: "Branscombe",
    edad: 64,
    sexo: "Female",
    posicion: "Mediocampista",
    salario: 94,
    pieDominante: "Derecho",
  },
  {
    id: 17,
    nombre: "Beverlie",
    apellido: "Fawloe",
    edad: 21,
    sexo: "Female",
    posicion: "Arquero",
    salario: 64,
    pieDominante: "Izquierdo",
  },
  {
    id: 18,
    nombre: "Sarena",
    apellido: "Batters",
    edad: 92,
    sexo: "Female",
    posicion: "Defensor",
    salario: 17,
    pieDominante: "Derecho",
  },
  {
    id: 19,
    nombre: "Lynnet",
    apellido: "MacDiarmid",
    edad: 33,
    sexo: "Female",
    posicion: "Defensor",
    salario: 17,
    pieDominante: "Derecho",
  },
  {
    id: 20,
    nombre: "Ly",
    apellido: "Cousins",
    edad: 75,
    sexo: "Male",
    posicion: "Arquero",
    salario: 67,
    pieDominante: "Izquierdo",
  },
];
